Add title, categories, introduction, related work and fix language and typos in fingerprint techniques
cs3235-autoauth/report pull request #2
Opened 2018-11-08 17:30 UTC by Xenonym

Apart from adding the introduction and related work, I also added:
- title
- author info
- categories
- keywords
and fixed the typos and language weirdness in the fingerprint technology section.

@githubxxcc please help check I didn't mess up the latex! ><

2018-11-08 18:02 UTC, KeithSOC requested changes
Great! 👍 Just some minor changes required~

2018-11-08 18:02 UTC, KeithSOC commented on paper.tex
> +Other than the informative objects mentioned earlier (\verb|navigator| and \verb|screen|), JavaScript can also be used to identify users indirectly, such as obtaining  browsing history or fine-graine
Do take note of extra space here:

```suggestion
Other than the informative objects mentioned earlier (\verb|navigator| and \verb|screen|), JavaScript can also be used to identify users indirectly, such as obtaining browsing history or fine-grained timing information of the JavaScript engine at different browsers.
```

2018-11-08 18:02 UTC, KeithSOC commented on paper.tex
> +Plugins are equipped with capabilities to access the software and hardware properties of the underlying system. One of these common plugins is Flash that is used for displaying videos and games in th
Do take note of extra space here:

```suggestion
Plugins are equipped with capabilities to access the software and hardware properties of the underlying system. One of these common plugins is Flash that is used for displaying videos and games in the \verb|.swf| format. In order for the web pages to use Flash effectively, Flash exposes APIs to query information about the operating system, as well as the specific version of Flash installed.
```

2018-11-08 18:02 UTC, KeithSOC commented on paper.tex
> +A browser extension is a special software component that adds extra functionality to the browser, such as RSS reader or ad-blockers. Extensions are different from plugins as extensions provide additi
Do take note of extra space here:

```suggestion
A browser extension is a special software component that adds extra functionality to the browser, such as RSS reader or ad-blockers. Extensions are different from plugins as extensions provide additional functionality in the browser itself while plugins enable additional functionality for rendering a web page. Take one of the extensions that expose additional
```

2018-11-08 18:02 UTC, KeithSOC commented on paper.tex
> +Such a strategy can be combined two-factor authentification. For example, in the event where the device used for receiving SMS is stolen, a fingerprint of the stolen device might reveal the unusual s
```suggestion
Such a strategy can be combined two-factor authentication. For example, in the event where the device used for receiving SMS is stolen, a fingerprint of the stolen device might reveal the unusual state of it as the fingerprint check failed, which leads to additional security checks.
```

2018-11-09 00:53 UTC, githubxxcc commented
LGTM. Thanks for the typo and english check. Should have done that by my own.

2018-11-09 00:53 UTC, merged